modLoader="lowcodefml"
loaderVersion="[42,]"
license="None"

[[mods]]
modId="create_mortar"
version="0.1.7c"
displayname="Create: Mortar"
description="Recipe changes and create add on compat"
dependencies="AFTER:*"
logoFile = "Mortar.png"

[[dependencies.create_mortar]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"

[[dependencies.create_mortar]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="createindustry"
mandatory= false
versionRange="[0.8.0b,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="railways"
mandatory= false
versionRange="[1.6.1+forge-mc1.19.2,)"
ordering="AFTER"
side="BOTH"


[[dependencies.create_mortar]]
modId="createbigcannons"
mandatory= false
versionRange="[0.5.3.b,)"
ordering="AFTER"
side="BOTH"